package io.jafar.parser;

import it.unimi.dsi.fastutil.longs.Long2ObjectMap;
import it.unimi.dsi.fastutil.longs.Long2ObjectOpenHashMap;

public final class Deserializers {
    private final Long2ObjectMap<JFRValueDeserializer<?>> deserializers = new Long2ObjectOpenHashMap<>();

    public void addDeserializer(long id, JFRValueDeserializer<?> deserializer) {
        deserializers.put(id, deserializer);
    }

    // Used from handler generated bytecode
    public <T> JFRValueDeserializer<?> getDeserializer(long id) {
        return deserializers.get(id);
    }

    public void clear() {
        deserializers.clear();
    }
}
